### ISSUE TITLE
TreeLDR layout hydration

### ISSUE THREAD

**Issue by cobward** [spruceid/treeldr#155]
It would be helpful to have a Rust library which can perform [de]hydration operations on data and RDF datasets for a given TreeLDR layout.

- [x] a function that takes a TreeLDR layout definition and raw data, and outputs an RDF dataset containing the triples from the raw data that matched the layout definition
- [x] a function that takes a TreeLDR layout definition and an RDF dataset, and outputs a rendered data object containing the data from the RDF dataset that matched the layout definition

**Comment by timothee-haudebourg** [comment]
Solved in branch [`v0.2`](https://github.com/spruceid/treeldr/tree/v0.2).
 - The entry point to the "hydrator" is [treeldr_layouts::distill::hydrate](https://github.com/spruceid/treeldr/blob/0f999c7087136b7fdf0588aad1c2e2f32cb4c1ae/layouts/src/distill/hy.rs#L51C8-L51C8)
 - The entry point to the "dehadrator" is [treeldr_layouts::distill::dehydrate](https://github.com/spruceid/treeldr/blob/0f999c7087136b7fdf0588aad1c2e2f32cb4c1ae/layouts/src/distill/de.rs#L59)
